# Generated by Django 3.2 on 2021-06-23 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=300)),
                ('TipoPessoa', models.CharField(choices=[('F', 'Física'), ('J', 'Juridica')], default='F', max_length=1)),
                ('CpfCnpj', models.CharField(max_length=14)),
                ('Estado', models.CharField(max_length=2)),
                ('Cidade', models.CharField(max_length=150)),
                ('Bairro', models.CharField(max_length=300)),
                ('Endereco', models.CharField(max_length=300)),
                ('Cep', models.CharField(max_length=9)),
                ('TipoEntidade', models.CharField(choices=[('R', 'Remetente'), ('D', 'Destinatário'), ('T', 'Tomadora')], default='R', max_length=1)),
                ('Email', models.CharField(max_length=300)),
                ('Telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rota12.entidade')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
