# Generated by Django 3.2 on 2021-07-09 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=300)),
                ('TipoPessoa', models.CharField(choices=[('F', 'Física'), ('J', 'Juridica')], default='F', max_length=1)),
                ('CpfCnpj', models.CharField(max_length=14, unique=True)),
                ('Estado', models.CharField(max_length=2)),
                ('Cidade', models.CharField(max_length=150)),
                ('Bairro', models.CharField(max_length=300)),
                ('Endereco', models.CharField(max_length=300)),
                ('Cep', models.CharField(max_length=9)),
                ('TipoEntidade', models.CharField(choices=[('R', 'Remetente'), ('D', 'Destinatário'), ('T', 'Tomadora')], default='R', max_length=1)),
                ('Email', models.CharField(max_length=300)),
                ('Telefone', models.CharField(max_length=15)),
                ('Saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField(default=0)),
                ('Acesso', models.CharField(default='ACESSO', max_length=100)),
                ('Conteudo', models.CharField(default='CONTEUDO', max_length=500)),
                ('ValorUm', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ValorDois', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ValorTres', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField(auto_now=True)),
                ('Descricao', models.CharField(max_length=500)),
                ('CreditoDebito', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], default='C', max_length=1)),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rota12.entidade')),
            ],
        ),
    ]
