# Generated by Django 3.2 on 2021-07-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='Saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='CpfCnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
