# Generated by Django 3.2 on 2021-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='Complemento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entidade',
            name='Numero',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
