# Generated by Django 3.2 on 2021-07-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota12', '0002_auto_20210709_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField(default=0, max_length=100)),
                ('Acesso', models.CharField(default='ACESSO', max_length=100)),
                ('Conteudo', models.CharField(default='CONTEUDO', max_length=500)),
                ('ValorUm', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ValorDois', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ValorTres', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
