# Generated by Django 3.2 on 2021-07-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota12', '0004_alter_parametros_codigo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametros',
            new_name='Parametro',
        ),
    ]
