# Generated by Django 3.2 on 2021-07-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota12', '0005_rename_parametros_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField(auto_now=True)),
                ('Descricao', models.CharField(max_length=500)),
                ('CreditoDebito', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], default='C', max_length=1)),
                ('Valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rota12.entidade')),
            ],
        ),
    ]
